2024-11-20 01:55:53,424 ERROR: Registration error: Tasks.subtasks and back-reference Tasks.parent are both of the same direction symbol('ONETOMANY').  Did you mean to set remote_side on the many-to-one side ? [in /Users/yashvardhansharma/Downloads/webapp162/backend/core/blueprints/bp_auth.py:109]
Traceback (most recent call last):
  File "/Users/yashvardhansharma/Downloads/webapp162/backend/core/blueprints/bp_auth.py", line 86, in register
    new_user = Users(
               ^^^^^^
  File "<string>", line 4, in __init__
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 476, in _initialize_instance
    manager.dispatch.init(self, args, kwargs)
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/event/attr.py", line 346, in __call__
    fn(*args, **kw)
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 3716, in _event_on_init
    instrumenting_mapper._check_configure()
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 1941, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 3527, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 3566, in _do_configure_registries
    mapper._post_configure_properties()
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 1958, in _post_configure_properties
    prop.init()
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/interfaces.py", line 231, in init
    self.do_init()
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2155, in do_init
    self._generate_backref()
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2488, in _generate_backref
    mapper._configure_property(backref_key, relationship)
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 1850, in _configure_property
    prop.init()
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/interfaces.py", line 231, in init
    self.do_init()
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2155, in do_init
    self._generate_backref()
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2491, in _generate_backref
    self._add_reverse_property(self.back_populates)
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2094, in _add_reverse_property
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Tasks.subtasks and back-reference Tasks.parent are both of the same direction symbol('ONETOMANY').  Did you mean to set remote_side on the many-to-one side ?
2024-11-20 01:56:20,687 ERROR: Registration error: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class Tasks->tasks'. Original exception was: Tasks.subtasks and back-reference Tasks.parent are both of the same direction symbol('ONETOMANY').  Did you mean to set remote_side on the many-to-one side ? [in /Users/yashvardhansharma/Downloads/webapp162/backend/core/blueprints/bp_auth.py:109]
Traceback (most recent call last):
  File "/Users/yashvardhansharma/Downloads/webapp162/backend/core/blueprints/bp_auth.py", line 86, in register
    new_user = Users(
               ^^^^^^
  File "<string>", line 4, in __init__
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 476, in _initialize_instance
    manager.dispatch.init(self, args, kwargs)
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/event/attr.py", line 346, in __call__
    fn(*args, **kw)
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 3716, in _event_on_init
    instrumenting_mapper._check_configure()
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 1941, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 3527, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/Users/yashvardhansharma/Downloads/webapp162/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 3562, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class Tasks->tasks'. Original exception was: Tasks.subtasks and back-reference Tasks.parent are both of the same direction symbol('ONETOMANY').  Did you mean to set remote_side on the many-to-one side ?
2024-11-20 01:57:14,281 INFO: Todo application startup [in /Users/yashvardhansharma/Downloads/webapp162/backend/run.py:84]
2024-11-20 01:57:17,531 INFO: Todo application startup [in /Users/yashvardhansharma/Downloads/webapp162/backend/run.py:84]
2024-11-20 01:57:28,526 ERROR: Registration error: 'JWT_EXPIRATION' [in /Users/yashvardhansharma/Downloads/webapp162/backend/core/blueprints/bp_auth.py:109]
Traceback (most recent call last):
  File "/Users/yashvardhansharma/Downloads/webapp162/backend/core/blueprints/bp_auth.py", line 96, in register
    token = create_token(new_user.id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashvardhansharma/Downloads/webapp162/backend/core/blueprints/bp_auth.py", line 30, in create_token
    {'user_id': user_id, 'exp': datetime.utcnow() + current_app.config['JWT_EXPIRATION']},
                                                    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'JWT_EXPIRATION'
2024-11-20 02:00:52,429 INFO: Todo application startup [in /Users/yashvardhansharma/Downloads/webapp162/backend/run.py:85]
2024-11-20 02:00:55,651 INFO: Todo application startup [in /Users/yashvardhansharma/Downloads/webapp162/backend/run.py:94]
2024-11-20 02:02:17,238 INFO: Todo application startup [in /Users/yashvardhansharma/Downloads/webapp162/backend/run.py:94]
2024-11-20 02:02:17,386 INFO: Todo application startup [in /Users/yashvardhansharma/Downloads/webapp162/backend/run.py:94]
